"""Study Australia scholarships example configuration.

Selectors were taken from the live rendered DOM on 2026-08-21.
They are stored here as a documented fixture, not hard-coded into the engine.
"""

from scraper.constants import (
    DATA_TEXT,
    DATA_URL,
    JOB_STATUS_ACTIVE,
    PAGINATION_QUERY,
    SCOPE_DETAIL_PAGE,
    SCOPE_RESULT_ITEM,
    SCOPE_SYSTEM,
    SOURCE_COUNTER,
    STOP_MAX_PAGES,
    STOP_NO_NEW_DETAIL_URLS,
    STOP_NO_RESULT_ITEMS,
    STOP_REPEATED_PAGE,
    VALUE_ATTRIBUTE,
    VALUE_TEXT,
)

START_URL = "https://search.studyaustralia.gov.au/scholarships?page=1"
URL_TEMPLATE = "https://search.studyaustralia.gov.au/scholarships?page={{page}}"

STUDY_AUSTRALIA_JOB = {
    "name": "Study Australia Scholarships",
    "description": "Paginated scholarship listing from search.studyaustralia.gov.au.",
    "status": JOB_STATUS_ACTIVE,
    "start_url": START_URL,
    "url_template": URL_TEMPLATE,
    "http_method": "GET",
    "rendering_mode": "auto",
    "result_selector": ".scholarship-list-card",
    "detail_link_selector": "h3 a",
    "detail_link_attribute": "href",
    "follow_detail_pages": True,
    "unique_field_name": "detail_url",
    "maximum_pages": 100,
    "variables": [
        {
            "name": "page",
            "label": "Page",
            "source_type": SOURCE_COUNTER,
            "data_type": "integer",
            "required": True,
            "configuration": {"start_value": 1, "increment": 1, "maximum_value": 100},
        }
    ],
    "pagination_settings": {
        "mode": PAGINATION_QUERY,
        "parameter": "page",
        "variable": "page",
        "start": 1,
        "increment": 1,
        "maximum_pages": 100,
        "url_template": URL_TEMPLATE,
        "next_button_selector": 'a[aria-label="Next page"]',
        "stop_conditions": [
            STOP_NO_RESULT_ITEMS,
            STOP_NO_NEW_DETAIL_URLS,
            STOP_REPEATED_PAGE,
            STOP_MAX_PAGES,
        ],
    },
    "fields": [
        {
            "name": "scholarship_name",
            "label": "Scholarship Name",
            "scope": SCOPE_RESULT_ITEM,
            "selector": "h3 a",
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "required": True,
            "transformations": ["trim", "normalize_whitespace"],
        },
        {
            "name": "provider_name",
            "label": "Provider Name",
            "scope": SCOPE_RESULT_ITEM,
            "selector": 'a[aria-label^="Scholarship provider"]',
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "transformations": ["trim"],
        },
        {
            "name": "scholarship_value",
            "label": "Scholarship Value",
            "scope": SCOPE_RESULT_ITEM,
            "selector": "p.text-sm",
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "multiple": True,
            "transformations": [
                "trim",
                {"name": "regex_capture", "pattern": r"Award value\s*[-:]\s*(.+)"},
                {"name": "join_values", "delimiter": "; "},
            ],
        },
        {
            "name": "study_level",
            "label": "Study Level",
            "scope": SCOPE_RESULT_ITEM,
            "selector": "p.text-sm",
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "multiple": True,
            "transformations": [
                "trim",
                {"name": "regex_capture", "pattern": r"Level of study\s*[-:]\s*(.+)"},
                {"name": "join_values", "delimiter": "; "},
            ],
        },
        {
            "name": "closing_date",
            "label": "Closing Date",
            "scope": SCOPE_RESULT_ITEM,
            "selector": "p.text-sm",
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "multiple": True,
            "transformations": [
                "trim",
                {"name": "regex_capture", "pattern": r"Closing date\s*[-:]\s*(.+)"},
                {"name": "join_values", "delimiter": "; "},
            ],
        },
        {
            "name": "detail_url",
            "label": "Detail URL",
            "scope": SCOPE_RESULT_ITEM,
            "selector": "h3 a",
            "extraction_method": VALUE_ATTRIBUTE,
            "attribute_name": "href",
            "data_type": DATA_URL,
            "required": True,
            "unique": True,
            "transformations": ["trim", "resolve_absolute_url"],
        },
        {
            "name": "application_url",
            "label": "Application URL",
            "scope": SCOPE_RESULT_ITEM,
            "selector": 'a[aria-label^="Enquire about"]',
            "extraction_method": VALUE_ATTRIBUTE,
            "attribute_name": "href",
            "data_type": DATA_URL,
            "transformations": ["trim", "resolve_absolute_url"],
        },
        {
            "name": "description",
            "label": "Description",
            "scope": SCOPE_DETAIL_PAGE,
            "selector": ".content-body .col-span-4 p.mb-2:last-of-type",
            "extraction_method": VALUE_TEXT,
            "data_type": DATA_TEXT,
            "transformations": ["trim", "normalize_whitespace"],
        },
        {
            "name": "source_page",
            "label": "Source Page",
            "scope": SCOPE_SYSTEM,
            "data_type": "integer",
        },
        {
            "name": "source_url",
            "label": "Source URL",
            "scope": SCOPE_SYSTEM,
            "data_type": DATA_URL,
        },
        {
            "name": "scraped_at",
            "label": "Scraped At",
            "scope": SCOPE_SYSTEM,
            "data_type": "datetime",
        },
    ],
}
