# Generated by Django 4.2.9 on 2026-08-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_url', models.URLField(blank=True, max_length=2000)),
                ('url_template', models.CharField(blank=True, max_length=2000)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=8)),
                ('rendering_mode', models.CharField(choices=[('auto', 'Auto'), ('http', 'HTTP'), ('browser', 'Browser')], default='auto', max_length=16)),
                ('request_settings', models.JSONField(blank=True, default=dict)),
                ('pagination_settings', models.JSONField(blank=True, default=dict)),
                ('execution_settings', models.JSONField(blank=True, default=dict)),
                ('result_selector', models.CharField(blank=True, max_length=500)),
                ('result_list_selector', models.CharField(blank=True, max_length=500)),
                ('detail_link_selector', models.CharField(blank=True, max_length=500)),
                ('detail_link_attribute', models.CharField(default='href', max_length=80)),
                ('follow_detail_pages', models.BooleanField(default=False)),
                ('unique_field_name', models.CharField(blank=True, max_length=80)),
                ('duplicate_handling', models.CharField(choices=[('skip', 'Skip'), ('update', 'Update existing record'), ('keep', 'Keep duplicate')], default='skip', max_length=16)),
                ('maximum_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_records', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('wizard_step', models.CharField(default='basic', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scrape_jobs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VariableParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('source_type', models.CharField(choices=[('url_query', 'URL query parameter'), ('url_path', 'URL path segment'), ('counter', 'Counter'), ('fixed', 'Fixed value'), ('list', 'List of values'), ('html_element', 'HTML element'), ('html_attribute', 'HTML attribute'), ('regex', 'Regular-expression result'), ('page_number', 'Current page number'), ('request_url', 'Current request URL'), ('parent_record', 'Parent-record value'), ('system', 'System-generated value'), ('run_timestamp', 'Run timestamp')], max_length=32)),
                ('scope', models.CharField(choices=[('result_page', 'Result page'), ('result_item', 'Result item'), ('detail_page', 'Detail page'), ('variable', 'Variable'), ('system', 'System')], default='result_page', max_length=24)),
                ('selector', models.CharField(blank=True, max_length=500)),
                ('value_from', models.CharField(choices=[('text_content', 'Text content'), ('inner_html', 'Inner HTML'), ('attribute', 'Attribute'), ('existence', 'Element existence')], default='text_content', max_length=24)),
                ('attribute_name', models.CharField(blank=True, max_length=80)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date and time'), ('currency', 'Currency'), ('url', 'URL'), ('email', 'Email'), ('html', 'HTML'), ('json', 'JSON'), ('list', 'List')], default='text', max_length=24)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_number', models.PositiveIntegerField(editable=False)),
                ('job_version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('running', 'Running'), ('pausing', 'Pausing'), ('paused', 'Paused'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('current_phase', models.CharField(blank=True, max_length=32)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('pages_attempted', models.PositiveIntegerField(default=0)),
                ('pages_completed', models.PositiveIntegerField(default=0)),
                ('records_discovered', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('detail_pages_queued', models.PositiveIntegerField(default=0)),
                ('detail_pages_completed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scraper.scrapejob')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('result_page', 'Result page'), ('result_item', 'Result item'), ('detail_page', 'Detail page'), ('variable', 'Variable'), ('system', 'System')], default='result_item', max_length=24)),
                ('selector', models.CharField(blank=True, max_length=500)),
                ('extraction_method', models.CharField(choices=[('text_content', 'Text content'), ('inner_html', 'Inner HTML'), ('attribute', 'Attribute'), ('existence', 'Element existence')], default='text_content', max_length=24)),
                ('attribute_name', models.CharField(blank=True, max_length=80)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date and time'), ('currency', 'Currency'), ('url', 'URL'), ('email', 'Email'), ('html', 'HTML'), ('json', 'JSON'), ('list', 'List')], default='text', max_length=24)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('include_in_csv', models.BooleanField(default=True)),
                ('include_in_sqlite', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('event_type', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scraper.scraperun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('unique_key', models.CharField(blank=True, max_length=512)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('detail_url', models.URLField(blank=True, max_length=2000)),
                ('detail_url_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('partial', 'Partial'), ('failed', 'Failed')], default='valid', max_length=16)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scraper.scrapejob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scraper.scraperun')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='PageTestCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_url', models.URLField(max_length=2000)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('rendering_mode_used', models.CharField(blank=True, max_length=16)),
                ('javascript_likely', models.BooleanField(default=False)),
                ('sanitized_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_tests', to='scraper.scrapejob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('sqlite', 'SQLite')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_name', models.CharField(max_length=500)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_exports', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='scraper.scraperun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='variableparameter',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='scraper_variable_job_name_unique'),
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['job', 'status'], name='scraper_scr_job_id_f3144e_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['status', 'created_at'], name='scraper_scr_status_9426df_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['requested_by', '-created_at'], name='scraper_scr_request_507438_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapejob',
            index=models.Index(fields=['owner', 'status'], name='scraper_scr_owner_i_f4e65c_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapejob',
            index=models.Index(fields=['owner', '-updated_at'], name='scraper_scr_owner_i_b13f4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrapejob',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='scraper_job_owner_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='scrapejob',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='scraper_job_owner_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='scrapefield',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='scraper_field_job_name_unique'),
        ),
        migrations.AddIndex(
            model_name='scrapeevent',
            index=models.Index(fields=['run', 'created_at'], name='scraper_scr_run_id_8a9fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrecord',
            index=models.Index(fields=['job', 'scraped_at'], name='scraper_scr_job_id_df2181_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrecord',
            index=models.Index(fields=['run', 'status'], name='scraper_scr_run_id_3f9b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrecord',
            index=models.Index(fields=['run', 'unique_key'], name='scraper_scr_run_id_740e78_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrecord',
            index=models.Index(fields=['detail_url_hash'], name='scraper_scr_detail__7cf5f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='scrapedrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_key', ''), _negated=True), fields=('run', 'unique_key'), name='scraper_record_run_unique_key'),
        ),
        migrations.AddIndex(
            model_name='exportartifact',
            index=models.Index(fields=['run', 'format', 'status'], name='scraper_exp_run_id_cb2e1c_idx'),
        ),
    ]
