# Generated by Django 4.2.9 on 2026-08-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_scrape_job_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapefield',
            name='created_via',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='scrapefield',
            name='last_updated_via',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='origin_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='variableparameter',
            name='created_via',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='variableparameter',
            name='last_updated_via',
            field=models.CharField(default='manual', max_length=16),
        ),
    ]
